# Matrix Convolutions
### Assignment 5

In [82]:
import numpy as np
from numpy import linalg as LA
from hedgehog.hw05 import *
from scipy.constants import golden

import matplotlib.pyplot as plt

%load_ext autoreload
%aimport hedgehog.hw05
%autoreload 1

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


#### Question 1

See notes/assignment.

#### Question 2

In [124]:
A = np.array([[4, 3, 0],
              [3, 4, -1],
              [0, -1, 4]])
b = np.array([[24], [30], [-24]])
x_0 = np.array([[1], [1], [1]])

W = np.arange(0.1, 1.9, 0.01)
I = []
for w in W:
    x, i = gauss_seidel(A, b, x_0, w, tol=10e-8)
    I.append(i)

In [141]:
best_W = []
best_I = np.min(I)
for idx, w in enumerate(W):
    if I[idx] == best_I:
        best_W.append(w)
best_I = [best_I] * len(best_W)

print(best_W, best_I[0])

plt.figure(figsize=(15,8))
plt.title(r"Number of iterations vs. $\omega$", fontsize=15)
plt.xlabel(r"$\omega$", fontsize=15)
plt.ylabel(r"Number of iterations", fontsize=15)
plt.xticks(np.arange(0, 2, 0.1))
plt.yticks(np.arange(0, np.max(I) + 30, 30))
plt.scatter(W, I, color="dimgrey", marker="o", s=10, label="")
plt.scatter(best_W, best_I, color="orangered", marker="o", s=10, label="Optimal points")
# plt.legend()
# plt.show()
plt.savefig("../hw05_gauss_seidel.PNG", dpi=200)

[1.2199999999999995, 1.2299999999999995, 1.2399999999999995, 1.2499999999999996, 1.2599999999999996] 15


In [142]:
x, i = gauss_seidel(A, b, x_0, 1.6, tol=10e-8, isVerbose=False)
print(i)

38


#### Question 3

In [139]:
A = np.array([[3, 0, 1],
              [0, 5, 0],
              [-1, 1, -1]])
x_0 = np.array([[0.5, -0.1, 0.4],
                [0, 0.2, 0],
                [-0.4, 0.3, -1.5]])
I = np.eye(3)
print(LA.inv(A))

[[ 0.5 -0.1  0.5]
 [ 0.   0.2  0. ]
 [-0.5  0.3 -1.5]]


In [138]:
x_1 = np.matmul(x_0, 2*I - np.matmul(A, x_0))
x_2 = np.matmul(x_1, 2*I - np.matmul(A, x_1))
print(x_1)
print(x_2)

[[ 0.49 -0.1   0.51]
 [ 0.    0.2   0.  ]
 [-0.51  0.3  -1.47]]
[[ 0.4994 -0.1     0.501 ]
 [ 0.      0.2     0.    ]
 [-0.501   0.3    -1.4982]]


In [140]:
A_inv = np.array([[0.5, -0.1, 0.5],
                  [0, 0.2, 0],
                  [-0.5, 0.3, -1.5]])

print(A_inv - x_1)
print(A_inv - x_2)

[[ 1.00000000e-02  0.00000000e+00 -1.00000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e-02 -5.55111512e-17 -3.00000000e-02]]
[[ 6.00000000e-04  0.00000000e+00 -1.00000000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e-03 -5.55111512e-17 -1.80000000e-03]]


#### Question 4

In [20]:
A = np.array([[2, -1, 0, 0],
              [-1, 2, -1, 0],
              [0, -1, 2, -1],
              [0, 0, -1, 2]])
x_1 = np.array([[1], [1], [1], [1]])

eigenval_1, eigenvec_1 = power_method(A, x_1, max_iter=50, isVerbose=False)
print(eigenval_1)
print(eigenvec_1)

[2.618033988749895, 2.618033988749895, 2.618033988749895, 2.618033988749895]
[[ 2.61803399]
 [-1.61803399]
 [-1.61803399]
 [ 2.61803399]]


In [9]:
x_2 = np.array([[1], [1], [5], [1]])

eigenval_2, eigenvec_2 = power_method(A, x_2, max_iter=50, isVerbose=False)
print(np.sum(eigenval_2) / len(eigenval_2))
print(eigenvec_2)

3.6180339887498993
[[ 2.23606775]
 [-3.61803377]
 [ 3.61803395]
 [-2.23606805]]


In [11]:
print(np.matmul(A, eigenvec_1) - eigenval_1[0] * eigenvec_1)

print(np.matmul(A, eigenvec_2) - eigenval_2[0] * eigenvec_2)

[[0.]
 [0.]
 [0.]
 [0.]]
[[-5.57325635e-08]
 [ 2.36086924e-07]
 [-4.16441287e-07]
 [ 3.47552051e-07]]


In [12]:
w, v = LA.eig(A)
print(w)
print(v)

[3.61803399 2.61803399 0.38196601 1.38196601]
[[-0.37174803 -0.60150096 -0.37174803 -0.60150096]
 [ 0.60150096  0.37174803 -0.60150096 -0.37174803]
 [-0.60150096  0.37174803 -0.60150096  0.37174803]
 [ 0.37174803 -0.60150096 -0.37174803  0.60150096]]


In [34]:
LA.solve(v, x_1)

array([[ 4.81809524e-16],
       [-4.59505841e-01],
       [-1.94649798e+00],
       [-2.72249584e-16]])

In [42]:
-0.46 * v[:,1] - 1.95 * v[:,2]

array([1.00159911, 1.00192277, 1.00192277, 1.00159911])

#### Question 5

In [43]:
A = np.array([[2, -1, 1],
              [-1, 3, 2],
              [1, 2, 3]])
x_0 = np.array([[1], [1], [1]])

In [54]:
x_1 = np.matmul(A, x_0)
x_2 = np.matmul(A, x_1)
x_3 = np.matmul(A, x_2)

[[2]
 [4]
 [6]]
[[ 6]
 [22]
 [28]]
[[ 18]
 [116]
 [134]]


In [55]:
m_0 = np.matmul(x_2.T, x_2)[0][0]
m_1 = np.matmul(x_2.T, x_3)[0][0]
m_2 = np.matmul(x_3.T, x_3)[0][0]

q = m_1 / m_0
err = np.sqrt(m_2 / m_0 - q*q)
print("q = {:.7f}".format(q))
print("err = {:.7f}".format(err))

1304
6412
31736
q = 4.9171779
err = 0.3984779


In [57]:
eigenval, eigenvec = power_method(A, x_0, max_iter=100, isVerbose=False)
print(eigenval)
print(eigenvec)

[5.0, 5.0, 5.0]
[[4.4408921e-16]
 [5.0000000e+00]
 [5.0000000e+00]]


In [58]:
np.matmul(A, np.array([[0], [1], [1]]))

array([[0],
       [5],
       [5]])